# Generated by Django 4.2 on 2025-06-19 15:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('bgimage', models.ImageField(blank=True, null=True, upload_to='heroares')),
            ],
        ),
    ]
