# Generated by Django 4.2 on 2025-06-20 18:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_service1_service_img1_service_no1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_no1',
            name='title',
        ),
        migrations.AlterField(
            model_name='service1',
            name='name',
            field=ckeditor.fields.RichTextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='service_no1',
            name='no',
            field=ckeditor.fields.RichTextField(max_length=400),
        ),
    ]
